### ISSUE TITLE
Overhaul builder status

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/winnitron_reborn#106]
This was a temporary hack anyway.

Currently, trying to register a Winnitron just results in me getting an email and them having to wait until I respond to it. Change this so that anyone can register one but it has limited permissions (e.g., it's limited to official playlist(s) and isn't visible on the site (related: #100)) until they get a thumbs-up from an admin.

To get that thumbs-up: a process where they submit a photo of their Winnitron (even work-in-progress) or something. @mrmwiebe thoughts?

**Comment by mrmwiebe** [comment]
@aaronklaassen yeah that's a great idea.  Photos or whatever works, as long as an admin determines it's cool.
