### ISSUE TITLE
Search errors with blank kw param

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/winnitron_reborn#138]
`/search?kw=foobar` works just fine, but `/search` or `/search?foo=bar` etc does not because `kw` is blank:

```
A NoMethodError occurred in search#index:

  undefined method `gsub' for nil:NilClass
  app/models/search.rb:7:in `initialize'
```

It should just return an empty search result.

**Comment by ozmar-11** [comment]
can I take this one?
