### ISSUE TITLE
Sign up / log in via twitter

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/winnitron_reborn#3]
Who needs another account on another website, right? This should be required - no local-only registration.

**Comment by yigitozkavci** [comment]
Hi. Twitter API doesn't allow you to get e-mail, it's not guaranteed for Twitter user to have e-mail anyway. How about implementing Facebook and Github?

The reason is I don't want to make user's email NULLABLE, you probably also wouldn't. @aaronklaassen

**Comment by aaronklaassen** [comment]
@yigitozkavci Can you turn this into a PR so I can take a look at the changes more easily?

**Comment by yigitozkavci** [comment]
It already is a pr :) https://github.com/winnitron/winnitron_reborn/pull/18

**Comment by aaronklaassen** [comment]
Oh hah oops.
