### ISSUE TITLE
Games need screenshots

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/winnitron_reborn#4]
Allow devs to upload screenshots to attach to their games.
- [ ] upload on form
- [ ] display on `show` page

**Comment by lokhi** [comment]
Hi,
I can work on it if you want.

**Comment by aaronklaassen** [comment]
@lokhi Go for it. :)

**Comment by lokhi** [comment]
Where do you want upload screenshots Amazon S3 ?

**Comment by aaronklaassen** [comment]
@lokhi Yep. Do you have access to a bucket you can test locally with?

Also I just realized this doesn't say it above, but a single game should support multiple screenshot uploads.

**Comment by yigitozkavci** [comment]
@aaronklaassen @lokhi I am not the one working on this, but just if you don't know, there is an awesome gem which works flawlessly with Amazon S3 buckets: https://github.com/thoughtbot/paperclip

**Comment by aaronklaassen** [comment]
Yeah I've used paperclip before. It's a good candidate for this. @lokhi let me know if you have any questions or anything.

**Comment by lokhi** [comment]
Yeah paperclip is very easy to use. But I see in the Gemfile the s3_direct_upload gem. I think I will try with it to not add another dependencie to the project. What do you think about it?

**Comment by aaronklaassen** [comment]
I like that even better. 😄
