### ISSUE TITLE
Need to figure out how to handle images

### ISSUE THREAD

**Issue by mrmwiebe** [winnitron/winnitron_reborn#42]
I think one of the images that are uploaded to a game need to be auto included into the downloaded zip files with their names attached to the metadata file.  Right now, the launcher is still looking for a .png file that has the same name as the .exe and folder.

**Comment by aaronklaassen** [comment]
We'll add an image URL to the API response that the launcher use to download and save.

**Comment by mrmwiebe** [comment]
I think this works now correct?

**Comment by aaronklaassen** [comment]
Ah, yeah. I didn't close it with #44 because I was thinking of this as a more general "managing photos" feature but you're right - this is API-only.
