### ISSUE TITLE
Page titles

### ISSUE THREAD

**Issue by aaronklaassen** [winnitron/winnitron_reborn#5]
They all just say "The Winnitron Network". More specific: game titles, etc.

**Comment by yigitozkavci** [comment]
Hi there! I just started working on this issue, and is this title format okay?

`Dashboard - The Winnitron Network`
`Submit a Game - The Winnitron Network`

Or would we prefer titles without `The Winnitron Network`?

**Comment by aaronklaassen** [comment]
@yigitozkavci Yep that works 👍. Took a look at your commits - looks good. Just change up the tabs to using 2 spaces. 😄

**Comment by yigitozkavci** [comment]
Done @aaronklaassen

**Comment by aaronklaassen** [comment]
@yigitozkavci Perfect. Just create a pull request with your changes and I'll merge them in.

**Comment by yigitozkavci** [comment]
Here it is :) https://github.com/winnitron/winnitron_reborn/pull/17
